
const Items = [
  {
    id: 0,
    image: require('@/public/images/ItemImages/image 1.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 2,
    image: require('@/public/images/ItemImages/image 2.png'),
    name: "sqsqsqsq",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 3,
    image: require('@/public/images/ItemImages/image 6.png'),
    name: "Sylthqdqdqsderine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 4,
    image: require('@/public/images/ItemImages/image 4.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 5,
    image: require('@/public/images/ItemImages/image 1.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 6,
    image: require('@/public/images/ItemImages/image 6.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 7,
    image: require('@/public/images/ItemImages/image 7.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 8,
    image: require('@/public/images/ItemImages/image 8.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 9,
    image: require('@/public/images/ItemImages/image 9.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 10,
    image: require('@/public/images/ItemImages/image 1.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 11,
    image: require('@/public/images/ItemImages/image 2.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 12,
    image: require('@/public/images/ItemImages/image 4.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 13,
    image: require('@/public/images/ItemImages/image 6.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
  {
    id: 14,
    image: require('@/public/images/ItemImages/image 7.png'),
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
  },
];

export default Items
